"ui.background" = { bg = "base00" }
"ui.popup" = { bg = "base01" }
"ui.selection" = { bg = "base02", fg = "base06" }
"ui.gutter.selected" = { fg = "base0A" }
"ui.menu.selected" = { bg = "base0F" }
"ui.cursor.match" = { fg = "base0A" }
"ui.statusline.normal" = { bg = "base0E", fg = "base00" }
"ui.statusline.insert" = { bg = "base0C", fg = "base00" }
"ui.statusline.select" = { bg = "base0F", fg = "base00" }
"ui.statusline" = { bg = "base00", modifiers = ["bold"] }
"ui.statusline.active" = { modifiers = ["underlined"] }
"ui.statusline.inactive" = { fg = "base06" }

"error" = { fg = "base08" }
"diagnostic.error" = { underline = { color = "base09", style = "curl" } }

"constant.numeric" = { fg = "base08" }

"operator" = { fg = "base0A" }

"string" = { fg = "base0B" }

"keyword" = { fg = "base0E" }
"constant" = { fg = "base0E" }
"punctuation" = { fg = "base0E" }

"comment" = { fg = "base0C" }

"diff.plus" = { fg = "base0B" }
"diff.minus" = { fg = "base09" }
"diff.delta" = {fg = "base0F" }

[palette]
base00 = "#181818" # dark
base01 = "#453d41" # grey
base02 = "#665c7f" # lilac
base03 = "#9dae93" # super light greyish green? 
base04 = "#e4e4ef" # super light grey
base05 = "#f4f4ff" # super light grey 2 
base06 = "#f5f5f5" # white smoke
base08 = "#f43841" # red
base09 = "#c73c3f" # darker red
base0A = "#ffdd33" # yellow
base0B = "#73c936" # green
base0C = "#95a99f" # light blueish grey
base0D = "#96a6c8" # light skyblue
base0E = "#9e95c7" # light lilac
base0F = "#cc8c3c" # coral
